random_seed: 0
logs_root_dir: ./
dataset:
  name: lapa
  data_dir: /cleargrasp_hdd/datasets/LaPa
  batch_size: 16
  num_workers: 4
  resize_h: 256
  resize_w: 256
model:
  name: deeplabv3
  backbone: drn
  num_classes: 11
  output_stride: 8
  sync_bn: false
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0005
trainer:
  name: trainer
  gpus: 1
  accelerator: ddp
  precision: 16
  max_epochs: 3
  resume_from_checkpoint: null
  log_every_n_steps: 1
  benchmark: false
  deterministic: true
  fast_dev_run: false
  overfit_batches: 0.0
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
scheduler:
  name: disabled
logger:
  name: wandb
  entity: cleargrasp2
  project: shrek_debug
  run_name: null
  run_id: null
callbacks:
  name: standard
  early_stopping:
    monitor: Val/mIoU
    min_delta: 0.0005
    patience: 10
    mode: max
    verbose: false
  checkpoints:
    filename: best
    save_last: true
    save_top_k: 1
    monitor: Val/mIoU
    mode: max
    period: 10
    verbose: false
  log_media:
    max_samples: 10
    period_epoch: 1
    period_step: 0
    save_to_disk: true
    save_latest_only: true
    verbose: true
load_weights:
  name: disabled
