# @package _group_
name: standard

early_stopping:
  min_delta: 0.0005
  patience: 10

checkpoints:
  monitor: 'Val/mIoU'
  mode: 'max'
  period: 1
  save_last: null

log_media:
  max_images_to_log: 10
  logging_epoch_interval: 1
  logging_batch_interval: 0
