# @package _group_
name: standard

early_stopping:
  min_delta: 0.0005
  patience: 10

checkpoints:
  monitor: 'Val/mIoU'
  mode: 'max'
  period: 1
  save_last: null

log_media:
  max_samples: 10
  period_epoch: 1
  period_step: 0
  save_to_disk: true
