# @package _group_
name: deeplabv3
# Possible values for backbone: ['xception', 'resnet', 'drn']
backbone: "drn"
output_stride: 8  # Not used with 'drn' backbone
num_classes: 11
sync_bn: False  # Can use PL to sync batchnorm. This enables custom batchnorm code.
enable_amp: False  # Should always be false, since PL takes case of 16bit training
