random_seed: 0  # If None, seeds not set. If int, uses value to seed.

checkpoint_load:
  resume_training: True
  resume_wandb_run: True
  wandb_run_id: "1eerdi7o"
  checkpoints_filename: "epoch=1-step=9.ckpt"

defaults:
  - dataset: lapa
  - model: deeplabv3
  - optimizer: adam
  - trainer: standard
  - scheduler: disabled
  - logger: wandb
  - callbacks: standard

  # To disable any .log files
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: . # Set working dir to current directory
