
num_steps: 10000

defaults:
    - dataset: lapa
    - optimizer: adam
#    - scheduler: disabled
#    - model: deeplabv3

    # To disable any .log files
    - hydra/job_logging: disabled
    - hydra/hydra_logging: disabled

hydra:
    output_subdir: null  # Disable saving of config files. We'll do that ourselves.
    run:
        dir: .  # Set working dir to current directory
