# @package _group_
name: trainer

gpus: 1 # Denotes the number of gpus to use. Set CUDA_VISIBLE_DEVICES env var to control which gpus are used.
accelerator: "ddp"
precision: 16
fast_dev_run: False
max_epochs: 10
resume_from_checkpoint: null
log_every_n_steps: 1
overfit_batches: 0.0
limit_train_batches: 50
limit_val_batches: 50
limit_test_batches: 0.99
