# @package _group_
name: trainer

gpus: 1 # Denotes the number of gpus to use. Set CUDA_VISIBLE_DEVICES env var to control which gpus are used.
accelerator: "ddp"
precision: 16

max_epochs: 100
resume_from_checkpoint: null
log_every_n_steps: 1

# For deterministic runs
benchmark: False # If true enables cudnn.benchmark.
deterministic: True # If true enables cudnn.deterministic.

# Limit batches for debugging
fast_dev_run: False # If True, runs 1 batch of train, val and test to find any bugs (ie: a sort of unit test).
overfit_batches: 0.0 # Overfit a percent of training data (float) or a set number of batches (int)
limit_train_batches: 1.0 # How much of training dataset to check (floats = percent, int = num_batches)
limit_val_batches: 1.0
limit_test_batches: 1.0
